---
title: "Week3B - Window Functions"
author: "Muhammad Ali"
format:
  html:
    code-fold: false
    
execute:
  echo: true
  warning: false
  message: false

editor: visual
---

# Window Functions Analysis

## Approach

### Goal

The goal of this assignment is to utilize and understand the concept of <mark>Window Functions </mark> used in R or SQL.

### Window Functions

What is a window function? It preserves information from the previous row as it iterates through the next row.

Some functions include, average, sum or any type of function that involves grouping things.

### The Plan

The first thing to do is to generate a dataset, synthetic or based off real data, with an LLM or find a dataset on popular sites such as:

-   Kaggle

-   Google Databases

-   UCI Machine Learning Repository

Following that dataset, we need to do the following steps:

-   Clean the dataset (if necessary)

-   Understand window functions in SQL or R

-   Apply the concept of window functions for the dataset
